///////////////////////////////////////////////////////////
//	AUTHOR: Kex
//	DATE: 1/4/16
//	VERSION: 1.0
//	FILE: Server\Generator\Storage\generated_locations.sqf 
//	DESCRIPTION: Locations generated by location_constructor.sqf
///////////////////////////////////////////////////////////
/*
// non civ locations
task_locations = [];
outpost_locations = [];
hideout_locations = [];
structure_locations = [];
recon_locations = [];
checkpoint_locations = []:

// civ locations
medic_locations = [];
garage_locations = [];
shop_locations = [];
civ_locations = []

// location functions
KEX_fnc_all_unknown_locations =
{
	// returns all non civ locations
	task_locations + 
	outpost_locations +
	hideout_locations +
	structure_locations +
	recon_locations +
	checkpoint_locations;
};
KEX_fnc_all_civ_locations =
{
	// returns all civ locations
	medic_locations +
	garage_locations +
	shop_locations;
};
*/